language: php

php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

install:
    - composer install

script:
    - ./vendor/bin/phake build:all

after_success:
    - curl -s https://codecov.io/bash > /tmp/codecov.sh
    - chmod +x /tmp/codecov.sh
    - /tmp/codecov.sh -s build/logs

notifications:
    email:
        - webdev@qobocloud.com
